### PR TITLE
Add JS example.

### PR DESCRIPTION
**Pull request by zautumnz**

### CODE REVIEW

**Comment by zacanger** [comment]
Pinging @taylorchu because you have the most recent commits in the Uservoice org and this repo doesn't seem to have a maintainer. If this PR isn't wanted, I can close it. Just trying to clean up old PRs I have open.

**Review by Jfcurd — CHANGES_REQUESTED** [review]
@zacanger this JS addition looks good to me. 

We should however remove the usage example at the bottom of the file to coincide with the other examples in this repository.

**Comment by zautumnz** [comment]
:+1: Done @Jfcurd

**Review by Jfcurd — APPROVED** [review]

**Comment by Jfcurd** [comment]
@zacanger thanks for contributing! I'll go ahead and merge this.

**Pull request merged**
